### PR TITLE
Add a marker upon user click

### LINKED ISSUE #16: Put a dot or something on the clicked location
After user has tapped a location, it may help to place a dot or pin or something on that location so that if they switch to something else and then return to here then they have a visual reference of what location they'd pinned for which the data is displayed. Also on mobile screens it helps to get visual feedback of exactly which place the finger touched.

### PR DESCRIPTION
**Pull request by DaxServer**
This also removes the marker, if it is added earlier.
This adds a default Mapbox Marker.

Fixes #16 

There is one hiccup here.

If the user clicked on the map (adding the marker) and the IP geolocation comes after this event, then the marker stays but the constituency is updated to the geolocation. 

Which one should we display?
**User clicked location** since he is particularly interested, or the **geolocation**?

### CODE REVIEW

**Comment by batpad** [comment]
@SrihariThalla this looks great!

My vote would be to show `User clicked location` - so if the user clicks on the map before the geolocation succeeds, probably set some variable that we check after geolocate and just don't do anything with geolocation success if user has already clicked on something?

I guess an extended feature request would be:

Also add a "Locate Me" button or so on the map so if the user wants to jump to their location at any point, they can by clicking that -- but let's definitely not do that in this PR - this PR also - as is, looks good to me and I'm 👍 on merging if you want to do the check if user has clicked after.

**Comment by DaxServer** [comment]
Let me do the check and prefer the `user clicked location` 👍

**Comment by batpad** [comment]
Oh - also @SrihariThalla before merging, you will also need to commit and push the `dist/index.js` build file:

`npm run build`

And then add and commit the `dist/index.js` file. We can make a separate ticket about potentially doing this as a post-commit hook or something like that, but for now, adding that will make sure the code updates on the live site :)

**Comment by batpad** [comment]
@SrihariThalla question: should we also add the marker to wherever the user's position geolocates to? Like, if the user does not click on anything - the default behaviour is to just zoom into user location and show constituency details for the location.

This should just be calling the `addMarker` function or so from around https://github.com/publicmap/electionmap/blob/master/js/locate-user.js#L22

Another idea would be to just make the `addMarker` part of `showDataAtPoint` ? Since we'd always want the marker to be for wherever we're currently showing data? I don't think there's ever a situation where we'd want the marker position and the information to be out-of-sync, so putting it inside `showDataAtPoint` seems like it might be sane.

**Comment by DaxServer** [comment]
> Oh - also @SrihariThalla before merging, you will also need to commit and push the `dist/index.js` build file:
> 
> `npm run build`
> 
> And then add and commit the `dist/index.js` file. We can make a separate ticket about potentially doing this as a post-commit hook or something like that, but for now, adding that will make sure the code updates on the live site :)

Oh, I thought I read on Telegram that it's not required or something Arun said.

I'll push it at the end, once the PR is good to go.

**Comment by batpad** [comment]
> Oh, I thought I read on Telegram that it's not required or something Arun said.

Na - you just shouldn't edit `dist/index.js` directly - of course :-) - but unfortunately right now the build file is still needed as part of the repo (and required to update code on the live site).

**Comment by DaxServer** [comment]
> @SrihariThalla question: should we also add the marker to wherever the user's position geolocates to? Like, if the user does not click on anything - the default behaviour is to just zoom into user location and show constituency details for the location.
> 
> This should just be calling the `addMarker` function or so from around https://github.com/publicmap/electionmap/blob/master/js/locate-user.js#L22
> 
> Another idea would be to just make the `addMarker` part of `showDataAtPoint` ? Since we'd always want the marker to be for wherever we're currently showing data? I don't think there's ever a situation where we'd want the marker position and the information to be out-of-sync, so putting it inside `showDataAtPoint` seems like it might be sane.

A follow-up question is where to put the marker - geometric centre of the constituency or the lngLat reported by IP/browser geo?

- IP geo is more of a regional level and may not be accurate all the time.
- Browser geo depends on the WiFi nearby and if not, falls back to IP geo taking us back to the question above.

Or maybe, how about we highlight the constituency geometry (if we have access) instead of a marker?

**Comment by batpad** [comment]
> Or maybe, how about we highlight the constituency geometry (if we have access) instead of a marker?

Yeaa .. highlighting the constituency would be very cool.

Sooo .. I *think* we should be able to get the constituency from the GL map, and add a property to it like `selected=true` or something and then have a GL filter which styles `selected=true` to show a highlight.

This is probably a little bit of work, but sounds like it'd be very cool. @SrihariThalla happy to try talking this through and I can probably find some code examples to help.

(I'm okay merging the current marker stuff as is and working on this problem after, or doing so right now, up to you).

**Comment by DaxServer** [comment]
Let's merge this for now if you don't see any bugs as is. We can continue the next part in another PR.

Let me push the `dist js`

**Comment by batpad** [comment]
> Let's merge this for now if you don't see any bugs as is.

Seems to work well 👍

**Review by batpad — APPROVED** [review]

**Comment by DaxServer** [comment]
BTW, I had no way to test the Browser geolocation as the web page did not load on a secure origin. I hope the live version works as expected in this PR!

**Comment by batpad** [comment]
> BTW, I had no way to test the Browser geolocation as the web page did not load on a secure origin.

Yea, me too ;-) - YOLO - it should be live now :-)

**Pull request merged**
